# Generated by Django 4.1.6 on 2023-03-03 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpu_cooler', '0001_initial'),
        ('processors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_builder_class',
            name='cpu_cooler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpu_cooler.cpu_cooler'),
        ),
        migrations.AddField(
            model_name='product_added',
            name='cpu_cooler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpu_cooler.cpu_cooler'),
        ),
    ]
