# Generated by Django 4.1.6 on 2023-03-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0002_pc_builder_class_cpu_cooler_product_added_cpu_cooler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_added',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
