# Generated by Django 4.1.6 on 2023-03-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0003_alter_product_added_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_added',
            name='cpu_cooler',
        ),
        migrations.RemoveField(
            model_name='product_added',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='product_added',
            name='user',
        ),
        migrations.DeleteModel(
            name='pc_builder_class',
        ),
        migrations.DeleteModel(
            name='product_added',
        ),
    ]
