# Generated by Django 4.1.6 on 2023-03-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherboard_image_url', models.URLField(max_length=500)),
                ('motherboard_name', models.CharField(max_length=200)),
                ('motherboard_old_link', models.URLField(max_length=500)),
                ('motherboard_brand', models.CharField(max_length=200)),
                ('motherboard_model', models.CharField(max_length=200)),
                ('motherboard_chipset', models.CharField(max_length=200)),
                ('motherboard_form_factor', models.CharField(max_length=200)),
                ('motherboard_socket_type', models.CharField(max_length=200)),
                ('motherboard_memory_slot', models.CharField(max_length=200)),
                ('motherboard_max_memory_support', models.CharField(max_length=200)),
            ],
        ),
    ]
