# Generated by Django 4.1.6 on 2023-02-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_name', models.CharField(max_length=200)),
                ('processor_brand', models.CharField(max_length=200)),
                ('processor_model', models.CharField(max_length=200)),
                ('processor_speed', models.CharField(max_length=200)),
                ('processor_cores', models.CharField(max_length=200)),
                ('processor_socket_type', models.CharField(max_length=200)),
                ('processor_image_url', models.CharField(max_length=200)),
                ('processor_image_alt', models.CharField(max_length=200)),
            ],
        ),
    ]
