# Generated by Django 4.1.6 on 2023-02-18 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='processor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('processor_name', models.CharField(max_length=200)),
                ('processor_short_name', models.CharField(max_length=200)),
                ('processor_brand', models.CharField(max_length=200)),
                ('processor_url', models.CharField(max_length=200)),
                ('processor_core_count', models.CharField(max_length=200)),
                ('processor_performance_core_clock', models.CharField(max_length=200)),
                ('processor_performance_boost_clock', models.CharField(blank=True, max_length=200, null=True)),
                ('processor_integrated_graphics', models.CharField(max_length=200)),
                ('processor_tdp', models.CharField(max_length=200)),
                ('processor_smt', models.CharField(max_length=200)),
                ('processor_price', models.CharField(max_length=200)),
                ('processor_image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='product_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.processor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pc_builder_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.processor')),
            ],
        ),
    ]
