# Generated by Django 4.1.6 on 2023-02-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_new_processor_delete_processor'),
    ]

    operations = [
        migrations.CreateModel(
            name='processor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('processor_brand', models.CharField(max_length=200)),
                ('processor_cores', models.CharField(max_length=200)),
                ('processor_image_alt', models.CharField(max_length=200)),
                ('processor_image_url', models.CharField(max_length=200)),
                ('processor_model', models.CharField(max_length=200)),
                ('processor_name', models.CharField(max_length=200)),
                ('processor_socket_type', models.CharField(max_length=200)),
                ('processor_speed', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='new_processor',
        ),
    ]
