# Generated by Django 4.1.6 on 2023-02-14 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_new_processor_delete_processor'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.new_processor')),
            ],
        ),
        migrations.CreateModel(
            name='pc_builder_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.new_processor')),
            ],
        ),
    ]
