# Generated by Django 4.1.6 on 2023-02-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_added_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_added',
            name='user',
        ),
    ]
