# Generated by Django 4.1.7 on 2023-02-15 09:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_product_added_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_builder_class',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pc_builder_class',
            name='prod_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='pc_builder_class',
            name='session_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
