# Generated by Django 4.1.7 on 2023-02-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_pc_builder_class_completed_pc_builder_class_prod_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc_builder_class',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='pc_builder_class',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='pc_builder_class',
            name='session_id',
        ),
    ]
