# Generated by Django 4.1.6 on 2023-03-03 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processors', '0004_remove_product_added_cpu_cooler_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpu_cooler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_added',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpu_cooler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpu_cooler.cpu_cooler')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processors.processor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pc_builder_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_cooler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpu_cooler.cpu_cooler')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processors.processor')),
            ],
        ),
    ]
