# Generated by Django 4.1.6 on 2023-03-04 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0004_remove_product_added_cpu_cooler_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_product_added_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='processor_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processors.processor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='product_added',
        ),
    ]
