# Generated by Django 4.1.6 on 2023-03-04 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpu_cooler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_processor_added_delete_product_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='cpu_cooler_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_cooler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpu_cooler.cpu_cooler')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
