# Generated by Django 4.1.6 on 2023-03-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cpu_cooler_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu_cooler_added',
            name='exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processor_added',
            name='exists',
            field=models.BooleanField(default=False),
        ),
    ]
