# Generated by Django 4.1.6 on 2023-03-04 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motherboard', '0001_initial'),
        ('ram', '0002_rename_ram_speed_ram_field8'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphics_cards', '0004_remove_graphicscard_price_graphicscard_image_url_and_more'),
        ('home', '0005_cpu_cooler_added_exists_processor_added_exists'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAM_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exists', models.BooleanField(default=False)),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ram.ram')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='motherboard_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exists', models.BooleanField(default=False)),
                ('motherboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motherboard.motherboard')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='graphics_card_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exists', models.BooleanField(default=False)),
                ('graphics_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graphics_cards.graphicscard')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
