# Generated by Django 4.1.6 on 2023-03-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_image_url', models.URLField()),
                ('ram_name', models.CharField(max_length=200)),
                ('ram_old_url', models.URLField()),
                ('ram_brand', models.CharField(max_length=50)),
                ('ram_model', models.CharField(max_length=50)),
                ('ram_size', models.CharField(max_length=10)),
                ('ram_quantity', models.CharField(max_length=20)),
                ('ram_type', models.CharField(max_length=10)),
                ('ram_speed', models.CharField(max_length=20)),
                ('ram_dimm_type', models.CharField(max_length=20)),
                ('ram_cas_latency', models.CharField(max_length=10)),
            ],
        ),
    ]
