# Generated by Django 4.1.6 on 2023-03-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ram',
            old_name='ram_speed',
            new_name='Field8',
        ),
    ]
