# Generated by Django 4.1.6 on 2023-03-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cpu_cooler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpu_cooler_name', models.CharField(max_length=200)),
                ('cpu_cooler_brand', models.CharField(max_length=200)),
                ('cpu_cooler_model', models.CharField(max_length=200)),
                ('cpu_cooler_fan_rpm', models.CharField(max_length=200)),
                ('cpu_cooler_noise_level', models.CharField(max_length=200)),
                ('cpu_cooler_color', models.CharField(max_length=200)),
                ('cpu_cooler_price', models.CharField(max_length=200)),
                ('cpu_cooler_image_url', models.CharField(max_length=200)),
            ],
        ),
    ]
