# Generated by Django 4.1.6 on 2023-03-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics_cards', '0003_graphicscard_delete_ok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphicscard',
            name='price',
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='Image_URL',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='graphics_card_old_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='graphic_card_base_clock',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='graphic_card_brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='graphic_card_chipset',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='graphic_card_clock_speed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='graphic_card_frame_sync',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='graphic_card_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='graphic_card_interface',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='graphic_card_length',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='graphic_card_memory_interface',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='graphic_card_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='graphic_card_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
